name: Check YouTube Fast

on:
  schedule:
    # Cette ligne dit à GitHub de lancer le script TOUTES LES 5 MINUTES
    - cron: '*/5 * * * *'
  workflow_dispatch: # Permet de le lancer à la main pour tester

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests beautifulsoup4 lxml

      - name: Run YouTube Tracker
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python youtube_tracker.py

      - name: Commit changes
        # Sauvegarde le fichier pour ne pas recevoir 20 fois la même vidéo
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add last_videos.txt
          git commit -m "Update last videos log" || exit 0
          git push
